---
- name: Configuring the EC2 Instance
  hosts: localhost
  connection: local
  tasks:
      - name: generating temp cradentials
        sts_assume_role:
          role_arn: "arn:aws:iam::211831525993:role/launchec2"
          role_session_name: "someRoleSession"
          region: us-east-1
        register: assumed_role

      - name: create a security group in us-east-1
        ec2_group:
          name: test-SG
          description: an example ec2 group
          region: us-east-1
          aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
          aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
          security_token: "{{ assumed_role.sts_creds.session_token }}"
          rules:
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
        register: security_group
