- name: Devops-Production
  hosts: localhost
  gather_facts: false
  vars:
    instance_ids:
      - 'i-06ffa6ded29617a44'
      
    region: ap-south-1
  tasks:
    - name: Devops-Production
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: '{{ ec2_state }}'
        name: '{{ ec2_tag }}'
        wait: True
        vpc_subnet_id: subnet-29e63245
        assign_public_ip: yes
