version: "2"
services:
### Refrance: https://www.digitalocean.com/community/tutorials/how-to-install-nagios-4-and-monitor-your-servers-on-ubuntu-14-04 ###
  nagios:
    build:
      context: ..
      dockerfile: ./Nagios/Dockerfile.nagios
    image: nagios:monitor
    container_name: nagios_monitor
    volumes:
      - ./node:/usr/local/nagios/etc/servers/
#      - /usr/local/nagios:/usr/local/nagios
    restart: always
    ports:
      - "80:80"
      - "5666:5666"
    command: bash -c "/etc/init.d/xinetd start && /etc/init.d/apache2 start && /etc/init.d/nagios start && tail -f /dev/null"
