FROM ubuntu:latest
RUN apt-get update && apt-get install -y wget
RUN apt-get install nginx apache2-utils -y
RUN htpasswd -c /etc/nginx/htpasswd.users kibanaadmin
COPY ./ELK/config/nginx.default /etc/nginx/sites-available/default

#COPY ./dockerised-java/target/DockerExample.war /opt/tomcat/webapps/DockerExample.war
