version: "2"
services:

  elasticsearch:
    build:
      context: ..
      dockerfile: ./ELK/Dockerfile.elasticsearch
    image: elasticsearch:latest
    container_name: elasticsearch
    #privileged: true
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    command: bash -c "/etc/init.d/elasticsearch start && tail -f /dev/null"

  kibana:
    build:
      context: ..
      dockerfile: ./ELK/Dockerfile.kibana
    image: kibana:latest
    container_name: kibana_elk
    restart: always
    ports:
      - "5601:5601"
    command: bash -c "/etc/init.d/kibana start && tail -f /dev/null"


     

